# core
pydantic>=2.7
pyyaml>=6.0.1
tqdm>=4.66

# ingest
pymupdf>=1.24.9
Pillow>=10.4.0
pytesseract>=0.3.13
rapidfuzz>=3.9.2
# optional: docling (if you use it)
docling>=2.6.0; sys_platform != "win32"  # or pin suitable build for Windows

# retrieval / embedding
sentence-transformers>=2.7.0
chromadb>=0.5.6

# notebooks
ipykernel>=6.29
